name: Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Choose Identity Storage Type
        options:
        - vault
        - local

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run:
          ./docker/build_image.sh
        env:
          IDENTITY_STORE_TYPE: "${{ github.event.inputs.choice || 'vault' }}"

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./docker/publish_image.sh
