name: Build gRPC Web Build

on:
  workflow_dispatch:

jobs:
  grpc-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t ghcr.io/hyperledger-labs/grpc-web:latest -f docker/grpc-web/Dockerfile .

      - name: Push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/hyperledger-labs/grpc-web:latest
