name: On-demand build

on:
  workflow_dispatch:

jobs:
  apollo:
    needs: common
    uses: ./.github/workflows/apollo.yml
  athena:
    needs: common
    uses: ./.github/workflows/athena.yml
  common:
    uses: ./.github/workflows/common.yml
  stitch:
    needs: common
    uses: ./.github/workflows/stitch.yml
  grpc-web-docker-build:
    needs: [stitch, athena, apollo]
    uses: ./.github/workflows/grpc-web-docker.yml
  deploy:
    needs: grpc-web-build
    uses: ./.github/workflows/deploy.yml
